name: Supportstar
slug: supportstar
access: public

description: "This is to test and a boilerplate app.
Accepts newline"

category: Integration

tags: 
- tag1
- tag2

developer: 
  name: rajat
  email: rajat@liftoffllc.com
  twitter: "technorajat"
  github: rajat-123

# The following config keys are used by Action Handlers
# Set button 'overlay' to true, if you want to have an overlay
# The valid values for screens are [ticket, all, unassigned, my, groups]
# Remove the following section if you do not want to define Action Handlers
 
action:
  button:
    overlay: false
    screens: 
    - ticket
    - all
    - unassigned
    label: Send To Supportstar
